#![deny(unsafe_op_in_unsafe_fn)]

//! Isolated HPy Universal adapter boundary.
//!
//! The host provides strict shared-library validation, process pinning, scoped
//! handles, H1 scalar APIs and the H2 container/object/call surface. APIs outside
//! the published capability inventory remain fail-closed.

mod host;
mod loader;

pub use host::{HostError, UniversalModule};
pub use loader::{LoadError, PinnedUniversalModule};

use std::{error::Error, fmt};

/// Machine-readable source manifest shipped with this crate.
pub const MANIFEST_TOML: &str = include_str!("../abi/hpy-0.9.0-universal.toml");

/// Exact upstream revisions used by the compatibility contract.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UpstreamPin {
    pub hpy_version: &'static str,
    pub hpy_git_tag: &'static str,
    pub hpy_docs_revision: &'static str,
    pub hpy_sdist_sha256: &'static str,
    pub ahpy_git_revision: &'static str,
}

pub const UPSTREAM: UpstreamPin = UpstreamPin {
    hpy_version: "0.9.0",
    hpy_git_tag: "0.9.0",
    hpy_docs_revision: "f6114734",
    hpy_sdist_sha256: "4545310f3a7f9ac249c0f19a80a9b05f46565afb62b7e9225b79493b7b6c70cc",
    ahpy_git_revision: "880d46d7d348df759ef062711ab3b4876bd648b8",
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UniversalAbi {
    pub name: &'static str,
    pub major: u32,
    pub minor: u32,
    pub tag: &'static str,
    pub public_header: &'static str,
    pub context_header: &'static str,
    pub context_first_slot: u16,
    pub context_last_slot: u16,
    pub context_slot_count: u16,
}

pub const UNIVERSAL_ABI: UniversalAbi = UniversalAbi {
    name: "universal",
    major: 0,
    minor: 0,
    tag: "hpy0",
    public_header: "hpy/devel/include/hpy.h",
    context_header: "hpy/devel/include/hpy/universal/autogen_ctx.h",
    context_first_slot: 0,
    context_last_slot: 262,
    context_slot_count: 263,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Platform {
    Linux,
    MacOs,
    Windows,
}

impl Platform {
    #[must_use]
    pub const fn universal_suffix(self) -> &'static str {
        match self {
            Self::Linux | Self::MacOs => ".hpy0.so",
            Self::Windows => ".hpy0.pyd",
        }
    }

    #[must_use]
    pub const fn current() -> Option<Self> {
        if cfg!(target_os = "linux") {
            Some(Self::Linux)
        } else if cfg!(target_os = "macos") {
            Some(Self::MacOs)
        } else if cfg!(target_os = "windows") {
            Some(Self::Windows)
        } else {
            None
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ModuleSymbols {
    pub required_major: String,
    pub required_minor: String,
    pub initialize_context: String,
    pub initialize_module: String,
}

/// Construct all Universal ABI symbols generated by `HPy_MODINIT`.
pub fn module_symbols(module_name: &str) -> Result<ModuleSymbols, ModuleNameError> {
    validate_module_name(module_name)?;
    Ok(ModuleSymbols {
        required_major: format!("get_required_hpy_major_version_{module_name}"),
        required_minor: format!("get_required_hpy_minor_version_{module_name}"),
        initialize_context: format!("HPyInitGlobalContext_{module_name}"),
        initialize_module: format!("HPyInit_{module_name}"),
    })
}

/// Validate a plain C identifier, the only safe input for HPy init symbols.
pub fn validate_module_name(module_name: &str) -> Result<(), ModuleNameError> {
    let mut bytes = module_name.bytes();
    let Some(first) = bytes.next() else {
        return Err(ModuleNameError);
    };
    if !(first == b'_' || first.is_ascii_alphabetic())
        || !bytes.all(|byte| byte == b'_' || byte.is_ascii_alphanumeric())
    {
        return Err(ModuleNameError);
    }
    Ok(())
}

/// Validate the Universal module filename contract.
pub fn validate_universal_filename(
    module_name: &str,
    file_name: &str,
    platform: Platform,
) -> Result<(), ModuleFileError> {
    validate_module_name(module_name).map_err(|_| ModuleFileError)?;
    let expected = format!("{module_name}{}", platform.universal_suffix());
    if file_name == expected {
        Ok(())
    } else {
        Err(ModuleFileError)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ModuleNameError;

impl fmt::Display for ModuleNameError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("HPy module name must be a non-empty ASCII C identifier")
    }
}

impl Error for ModuleNameError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ModuleFileError;

impl fmt::Display for ModuleFileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("filename does not match the pinned HPy Universal ABI contract")
    }
}

impl Error for ModuleFileError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityState {
    Available,
    Unavailable,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Capability {
    pub id: &'static str,
    pub planned_milestone: &'static str,
    pub state: CapabilityState,
}

const fn unavailable(id: &'static str, planned_milestone: &'static str) -> Capability {
    Capability {
        id,
        planned_milestone,
        state: CapabilityState::Unavailable,
    }
}

const fn available(id: &'static str, planned_milestone: &'static str) -> Capability {
    Capability {
        id,
        planned_milestone,
        state: CapabilityState::Available,
    }
}

/// Exhaustive coarse-grained capability inventory.
///
/// APIs not represented here are also unavailable: lookup is fail-closed.
pub const CAPABILITIES: &[Capability] = &[
    available("module-init", "H1"),
    available("local-handles", "H1"),
    available("integer-conversion", "H1"),
    available("unicode", "H1"),
    available("exception-state", "H1"),
    available("containers-builders", "H2"),
    available("attributes-items-calls", "H2"),
    available("scalars-exceptions", "H2"),
    unavailable("globals", "H3"),
    unavailable("fields", "H3"),
    unavailable("types", "H4"),
    unavailable("buffer", "H5"),
    unavailable("execution-state", "H5"),
    unavailable("debug-context", "H6"),
    unavailable("trace-context", "H6"),
];

/// HPy functions that Tonic can currently execute.
pub const IMPLEMENTED_FUNCTIONS: &[&str] = &[
    "HPy_Dup",
    "HPy_Close",
    "HPyLong_FromInt32_t",
    "HPyLong_FromUInt32_t",
    "HPyLong_FromInt64_t",
    "HPyLong_FromUInt64_t",
    "HPyLong_FromSize_t",
    "HPyLong_FromSsize_t",
    "HPyLong_AsInt32_t",
    "HPyLong_AsUInt32_t",
    "HPyLong_AsUInt32_tMask",
    "HPyLong_AsInt64_t",
    "HPyLong_AsUInt64_t",
    "HPyLong_AsUInt64_tMask",
    "HPyLong_AsSize_t",
    "HPyLong_AsSsize_t",
    "HPyLong_AsVoidPtr",
    "HPyLong_AsDouble",
    "HPyFloat_FromDouble",
    "HPyFloat_AsDouble",
    "HPyBool_FromBool",
    "HPyUnicode_FromString",
    "HPyUnicode_AsUTF8AndSize",
    "HPyErr_SetString",
    "HPyErr_SetObject",
    "HPyErr_Occurred",
    "HPyErr_ExceptionMatches",
    "HPyErr_NoMemory",
    "HPyErr_Clear",
    "HPyList_Check",
    "HPyList_New",
    "HPyList_Append",
    "HPyDict_Check",
    "HPyDict_New",
    "HPyTuple_Check",
    "HPyTuple_FromArray",
    "HPyListBuilder_New",
    "HPyListBuilder_Set",
    "HPyListBuilder_Build",
    "HPyListBuilder_Cancel",
    "HPyTupleBuilder_New",
    "HPyTupleBuilder_Set",
    "HPyTupleBuilder_Build",
    "HPyTupleBuilder_Cancel",
    "HPy_Length",
    "HPyCallable_Check",
    "HPy_CallTupleDict",
    "HPy_GetAttr",
    "HPy_GetAttr_s",
    "HPy_HasAttr",
    "HPy_HasAttr_s",
    "HPy_SetAttr",
    "HPy_SetAttr_s",
    "HPy_GetItem",
    "HPy_GetItem_i",
    "HPy_GetItem_s",
    "HPy_Contains",
    "HPy_SetItem",
    "HPy_SetItem_i",
    "HPy_SetItem_s",
    "HPy_Repr",
    "HPy_DelItem",
    "HPy_DelItem_i",
    "HPy_DelItem_s",
    "HPy_Call",
    "HPy_CallMethod",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FunctionCapability {
    pub name: &'static str,
    pub planned_milestone: &'static str,
    pub state: CapabilityState,
}

const fn available_function(
    name: &'static str,
    planned_milestone: &'static str,
) -> FunctionCapability {
    FunctionCapability {
        name,
        planned_milestone,
        state: CapabilityState::Available,
    }
}

/// Callable context surface. Later APIs remain absent and fail closed.
pub const PLANNED_FUNCTIONS: &[FunctionCapability] = &[
    available_function("HPy_Dup", "H1"),
    available_function("HPy_Close", "H1"),
    available_function("HPyLong_FromInt32_t", "H2"),
    available_function("HPyLong_FromUInt32_t", "H2"),
    available_function("HPyLong_FromInt64_t", "H1"),
    available_function("HPyLong_FromUInt64_t", "H2"),
    available_function("HPyLong_FromSize_t", "H2"),
    available_function("HPyLong_FromSsize_t", "H2"),
    available_function("HPyLong_AsInt32_t", "H2"),
    available_function("HPyLong_AsUInt32_t", "H2"),
    available_function("HPyLong_AsUInt32_tMask", "H2"),
    available_function("HPyLong_AsInt64_t", "H1"),
    available_function("HPyLong_AsUInt64_t", "H2"),
    available_function("HPyLong_AsUInt64_tMask", "H2"),
    available_function("HPyLong_AsSize_t", "H2"),
    available_function("HPyLong_AsSsize_t", "H2"),
    available_function("HPyLong_AsVoidPtr", "H2"),
    available_function("HPyLong_AsDouble", "H2"),
    available_function("HPyFloat_FromDouble", "H2"),
    available_function("HPyFloat_AsDouble", "H2"),
    available_function("HPyBool_FromBool", "H2"),
    available_function("HPyUnicode_FromString", "H1"),
    available_function("HPyUnicode_AsUTF8AndSize", "H1"),
    available_function("HPyErr_SetString", "H1"),
    available_function("HPyErr_SetObject", "H2"),
    available_function("HPyErr_Occurred", "H1"),
    available_function("HPyErr_ExceptionMatches", "H2"),
    available_function("HPyErr_NoMemory", "H2"),
    available_function("HPyErr_Clear", "H1"),
    available_function("HPyList_Check", "H2"),
    available_function("HPyList_New", "H2"),
    available_function("HPyList_Append", "H2"),
    available_function("HPyDict_Check", "H2"),
    available_function("HPyDict_New", "H2"),
    available_function("HPyTuple_Check", "H2"),
    available_function("HPyTuple_FromArray", "H2"),
    available_function("HPyListBuilder_New", "H2"),
    available_function("HPyListBuilder_Set", "H2"),
    available_function("HPyListBuilder_Build", "H2"),
    available_function("HPyListBuilder_Cancel", "H2"),
    available_function("HPyTupleBuilder_New", "H2"),
    available_function("HPyTupleBuilder_Set", "H2"),
    available_function("HPyTupleBuilder_Build", "H2"),
    available_function("HPyTupleBuilder_Cancel", "H2"),
    available_function("HPy_Length", "H2"),
    available_function("HPyCallable_Check", "H2"),
    available_function("HPy_CallTupleDict", "H2"),
    available_function("HPy_GetAttr", "H2"),
    available_function("HPy_GetAttr_s", "H2"),
    available_function("HPy_HasAttr", "H2"),
    available_function("HPy_HasAttr_s", "H2"),
    available_function("HPy_SetAttr", "H2"),
    available_function("HPy_SetAttr_s", "H2"),
    available_function("HPy_GetItem", "H2"),
    available_function("HPy_GetItem_i", "H2"),
    available_function("HPy_GetItem_s", "H2"),
    available_function("HPy_Contains", "H2"),
    available_function("HPy_SetItem", "H2"),
    available_function("HPy_SetItem_i", "H2"),
    available_function("HPy_SetItem_s", "H2"),
    available_function("HPy_Repr", "H2"),
    available_function("HPy_DelItem", "H2"),
    available_function("HPy_DelItem_i", "H2"),
    available_function("HPy_DelItem_s", "H2"),
    available_function("HPy_Call", "H2"),
    available_function("HPy_CallMethod", "H2"),
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityError {
    Unknown,
    Unavailable { planned_milestone: &'static str },
}

impl fmt::Display for CapabilityError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unknown => formatter.write_str("unknown HPy capability; rejected by default"),
            Self::Unavailable { planned_milestone } => write!(
                formatter,
                "HPy capability is unavailable; planned for milestone {planned_milestone}"
            ),
        }
    }
}

impl Error for CapabilityError {}

#[must_use]
pub fn capability(id: &str) -> Option<&'static Capability> {
    CAPABILITIES.iter().find(|capability| capability.id == id)
}

/// Require a capability while preserving fail-closed behavior.
pub fn require_capability(id: &str) -> Result<&'static Capability, CapabilityError> {
    let capability = capability(id).ok_or(CapabilityError::Unknown)?;
    match capability.state {
        CapabilityState::Available => Ok(capability),
        CapabilityState::Unavailable => Err(CapabilityError::Unavailable {
            planned_milestone: capability.planned_milestone,
        }),
    }
}

/// Require an HPy function while preserving the manifest's default-deny rule.
pub fn require_function(name: &str) -> Result<&'static FunctionCapability, CapabilityError> {
    let function = PLANNED_FUNCTIONS
        .iter()
        .find(|function| function.name == name)
        .ok_or(CapabilityError::Unknown)?;
    match function.state {
        CapabilityState::Available => Ok(function),
        CapabilityState::Unavailable => Err(CapabilityError::Unavailable {
            planned_milestone: function.planned_milestone,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pinned_context_layout_is_contiguous() {
        assert_eq!(
            UNIVERSAL_ABI.context_last_slot - UNIVERSAL_ABI.context_first_slot + 1,
            UNIVERSAL_ABI.context_slot_count
        );
        assert_eq!(UNIVERSAL_ABI.tag, "hpy0");
    }

    #[test]
    fn module_contract_is_strict() {
        let symbols = module_symbols("fib_native").unwrap();
        assert_eq!(
            symbols.required_major,
            "get_required_hpy_major_version_fib_native"
        );
        assert_eq!(
            symbols.required_minor,
            "get_required_hpy_minor_version_fib_native"
        );
        assert_eq!(
            symbols.initialize_context,
            "HPyInitGlobalContext_fib_native"
        );
        assert_eq!(symbols.initialize_module, "HPyInit_fib_native");

        for invalid in ["", "fib.mod", "fib-mod", "9fib", "fıb"] {
            assert_eq!(module_symbols(invalid), Err(ModuleNameError));
        }
    }

    #[test]
    fn filename_contract_rejects_wrong_abi_or_module() {
        assert_eq!(
            validate_universal_filename("fib", "fib.hpy0.so", Platform::Linux),
            Ok(())
        );
        assert_eq!(
            validate_universal_filename("fib", "fib.hpy0.so", Platform::MacOs),
            Ok(())
        );
        assert_eq!(
            validate_universal_filename("fib", "fib.hpy0.pyd", Platform::Windows),
            Ok(())
        );
        assert_eq!(
            validate_universal_filename("fib", "fib.cpython-313.so", Platform::Linux),
            Err(ModuleFileError)
        );
        assert_eq!(
            validate_universal_filename("fib", "other.hpy0.so", Platform::Linux),
            Err(ModuleFileError)
        );
    }

    #[test]
    fn published_capabilities_are_exact_and_unknown_apis_fail_closed() {
        for capability in CAPABILITIES {
            match capability.state {
                CapabilityState::Available => {
                    assert_eq!(require_capability(capability.id), Ok(capability));
                }
                CapabilityState::Unavailable => assert_eq!(
                    require_capability(capability.id),
                    Err(CapabilityError::Unavailable {
                        planned_milestone: capability.planned_milestone
                    })
                ),
            }
        }
        assert_eq!(
            require_capability("future-api"),
            Err(CapabilityError::Unknown)
        );
        assert_eq!(IMPLEMENTED_FUNCTIONS.len(), PLANNED_FUNCTIONS.len());
        for function in PLANNED_FUNCTIONS {
            assert_eq!(function.state, CapabilityState::Available);
            assert_eq!(require_function(function.name), Ok(function));
            assert!(IMPLEMENTED_FUNCTIONS.contains(&function.name));
        }
        assert_eq!(
            require_function("HPy_Future"),
            Err(CapabilityError::Unknown)
        );
    }

    #[test]
    fn published_manifest_matches_typed_inventory() {
        for needle in [
            UPSTREAM.hpy_version,
            UPSTREAM.hpy_git_tag,
            UPSTREAM.hpy_docs_revision,
            UPSTREAM.hpy_sdist_sha256,
            UPSTREAM.ahpy_git_revision,
            UNIVERSAL_ABI.tag,
        ] {
            assert!(
                MANIFEST_TOML.contains(needle),
                "missing manifest value: {needle}"
            );
        }
        for capability in CAPABILITIES {
            assert!(MANIFEST_TOML.contains(&format!("id = \"{}\"", capability.id)));
        }
        for function in PLANNED_FUNCTIONS {
            assert!(MANIFEST_TOML.contains(&format!("\"{}\"", function.name)));
        }
    }
}
