#![deny(unsafe_code)]

//! Isolated HPy Universal adapter boundary.
//!
//! Milestone H0 deliberately contains metadata and validation only. In
//! particular, [`CapabilityState::Unavailable`] means that no callable HPy
//! implementation is present yet.

use std::{error::Error, fmt};

/// Machine-readable source manifest shipped with this crate.
pub const MANIFEST_TOML: &str = include_str!("../abi/hpy-0.9.0-universal.toml");

/// Exact upstream revisions used by the compatibility contract.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UpstreamPin {
    pub hpy_version: &'static str,
    pub hpy_git_tag: &'static str,
    pub hpy_docs_revision: &'static str,
    pub hpy_sdist_sha256: &'static str,
    pub ahpy_git_revision: &'static str,
}

pub const UPSTREAM: UpstreamPin = UpstreamPin {
    hpy_version: "0.9.0",
    hpy_git_tag: "0.9.0",
    hpy_docs_revision: "f6114734",
    hpy_sdist_sha256: "4545310f3a7f9ac249c0f19a80a9b05f46565afb62b7e9225b79493b7b6c70cc",
    ahpy_git_revision: "880d46d7d348df759ef062711ab3b4876bd648b8",
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UniversalAbi {
    pub name: &'static str,
    pub major: u32,
    pub minor: u32,
    pub tag: &'static str,
    pub public_header: &'static str,
    pub context_header: &'static str,
    pub context_first_slot: u16,
    pub context_last_slot: u16,
    pub context_slot_count: u16,
}

pub const UNIVERSAL_ABI: UniversalAbi = UniversalAbi {
    name: "universal",
    major: 0,
    minor: 0,
    tag: "hpy0",
    public_header: "hpy/devel/include/hpy.h",
    context_header: "hpy/devel/include/hpy/universal/autogen_ctx.h",
    context_first_slot: 0,
    context_last_slot: 260,
    context_slot_count: 261,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Platform {
    Linux,
    MacOs,
    Windows,
}

impl Platform {
    #[must_use]
    pub const fn universal_suffix(self) -> &'static str {
        match self {
            Self::Linux | Self::MacOs => ".hpy0.so",
            Self::Windows => ".hpy0.pyd",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ModuleSymbols {
    pub required_major: String,
    pub required_minor: String,
    pub initialize_context: String,
    pub initialize_module: String,
}

/// Construct all Universal ABI symbols generated by `HPy_MODINIT`.
pub fn module_symbols(module_name: &str) -> Result<ModuleSymbols, ModuleNameError> {
    validate_module_name(module_name)?;
    Ok(ModuleSymbols {
        required_major: format!("get_required_hpy_major_version_{module_name}"),
        required_minor: format!("get_required_hpy_minor_version_{module_name}"),
        initialize_context: format!("HPyInitGlobalContext_{module_name}"),
        initialize_module: format!("HPyInit_{module_name}"),
    })
}

/// Validate a plain C identifier, the only safe input for HPy init symbols.
pub fn validate_module_name(module_name: &str) -> Result<(), ModuleNameError> {
    let mut bytes = module_name.bytes();
    let Some(first) = bytes.next() else {
        return Err(ModuleNameError);
    };
    if !(first == b'_' || first.is_ascii_alphabetic())
        || !bytes.all(|byte| byte == b'_' || byte.is_ascii_alphanumeric())
    {
        return Err(ModuleNameError);
    }
    Ok(())
}

/// Validate only the filename contract. Loading begins in milestone H1.
pub fn validate_universal_filename(
    module_name: &str,
    file_name: &str,
    platform: Platform,
) -> Result<(), ModuleFileError> {
    validate_module_name(module_name).map_err(|_| ModuleFileError)?;
    let expected = format!("{module_name}{}", platform.universal_suffix());
    if file_name == expected {
        Ok(())
    } else {
        Err(ModuleFileError)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ModuleNameError;

impl fmt::Display for ModuleNameError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("HPy module name must be a non-empty ASCII C identifier")
    }
}

impl Error for ModuleNameError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ModuleFileError;

impl fmt::Display for ModuleFileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("filename does not match the pinned HPy Universal ABI contract")
    }
}

impl Error for ModuleFileError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityState {
    Unavailable,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Capability {
    pub id: &'static str,
    pub planned_milestone: &'static str,
    pub state: CapabilityState,
}

const fn unavailable(id: &'static str, planned_milestone: &'static str) -> Capability {
    Capability {
        id,
        planned_milestone,
        state: CapabilityState::Unavailable,
    }
}

/// Exhaustive coarse-grained H0 capability inventory.
///
/// APIs not represented here are also unavailable: lookup is fail-closed.
pub const CAPABILITIES: &[Capability] = &[
    unavailable("module-init", "H1"),
    unavailable("local-handles", "H1"),
    unavailable("integer-conversion", "H1"),
    unavailable("unicode", "H1"),
    unavailable("exception-state", "H1"),
    unavailable("containers-builders", "H2"),
    unavailable("attributes-items-calls", "H2"),
    unavailable("globals", "H3"),
    unavailable("fields", "H3"),
    unavailable("types", "H4"),
    unavailable("buffer", "H5"),
    unavailable("execution-state", "H5"),
    unavailable("debug-context", "H6"),
    unavailable("trace-context", "H6"),
];

/// HPy functions that Tonic can currently execute.
///
/// H0 is inventory-only, so this list must remain empty until H1 supplies a
/// real context and runtime implementation.
pub const IMPLEMENTED_FUNCTIONS: &[&str] = &[];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FunctionCapability {
    pub name: &'static str,
    pub planned_milestone: &'static str,
    pub state: CapabilityState,
}

const fn unavailable_function(
    name: &'static str,
    planned_milestone: &'static str,
) -> FunctionCapability {
    FunctionCapability {
        name,
        planned_milestone,
        state: CapabilityState::Unavailable,
    }
}

/// First callable context surface planned for H1. Every entry still fails
/// closed in H0.
pub const PLANNED_FUNCTIONS: &[FunctionCapability] = &[
    unavailable_function("HPy_Dup", "H1"),
    unavailable_function("HPy_Close", "H1"),
    unavailable_function("HPyLong_FromInt64_t", "H1"),
    unavailable_function("HPyLong_AsInt64_t", "H1"),
    unavailable_function("HPyUnicode_FromString", "H1"),
    unavailable_function("HPyUnicode_AsUTF8AndSize", "H1"),
    unavailable_function("HPyErr_SetString", "H1"),
    unavailable_function("HPyErr_Occurred", "H1"),
    unavailable_function("HPyErr_Clear", "H1"),
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityError {
    Unknown,
    Unavailable { planned_milestone: &'static str },
}

impl fmt::Display for CapabilityError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unknown => formatter.write_str("unknown HPy capability; rejected by H0"),
            Self::Unavailable { planned_milestone } => write!(
                formatter,
                "HPy capability is unavailable; planned for milestone {planned_milestone}"
            ),
        }
    }
}

impl Error for CapabilityError {}

#[must_use]
pub fn capability(id: &str) -> Option<&'static Capability> {
    CAPABILITIES.iter().find(|capability| capability.id == id)
}

/// Require a capability while preserving H0's fail-closed behavior.
pub fn require_capability(id: &str) -> Result<&'static Capability, CapabilityError> {
    let capability = capability(id).ok_or(CapabilityError::Unknown)?;
    match capability.state {
        CapabilityState::Unavailable => Err(CapabilityError::Unavailable {
            planned_milestone: capability.planned_milestone,
        }),
    }
}

/// Require an HPy function while preserving the manifest's default-deny rule.
pub fn require_function(name: &str) -> Result<&'static FunctionCapability, CapabilityError> {
    let function = PLANNED_FUNCTIONS
        .iter()
        .find(|function| function.name == name)
        .ok_or(CapabilityError::Unknown)?;
    match function.state {
        CapabilityState::Unavailable => Err(CapabilityError::Unavailable {
            planned_milestone: function.planned_milestone,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pinned_context_layout_is_contiguous() {
        assert_eq!(
            UNIVERSAL_ABI.context_last_slot - UNIVERSAL_ABI.context_first_slot + 1,
            UNIVERSAL_ABI.context_slot_count
        );
        assert_eq!(UNIVERSAL_ABI.tag, "hpy0");
    }

    #[test]
    fn module_contract_is_strict() {
        let symbols = module_symbols("fib_native").unwrap();
        assert_eq!(
            symbols.required_major,
            "get_required_hpy_major_version_fib_native"
        );
        assert_eq!(
            symbols.required_minor,
            "get_required_hpy_minor_version_fib_native"
        );
        assert_eq!(
            symbols.initialize_context,
            "HPyInitGlobalContext_fib_native"
        );
        assert_eq!(symbols.initialize_module, "HPyInit_fib_native");

        for invalid in ["", "fib.mod", "fib-mod", "9fib", "fıb"] {
            assert_eq!(module_symbols(invalid), Err(ModuleNameError));
        }
    }

    #[test]
    fn filename_contract_rejects_wrong_abi_or_module() {
        assert_eq!(
            validate_universal_filename("fib", "fib.hpy0.so", Platform::Linux),
            Ok(())
        );
        assert_eq!(
            validate_universal_filename("fib", "fib.hpy0.so", Platform::MacOs),
            Ok(())
        );
        assert_eq!(
            validate_universal_filename("fib", "fib.hpy0.pyd", Platform::Windows),
            Ok(())
        );
        assert_eq!(
            validate_universal_filename("fib", "fib.cpython-313.so", Platform::Linux),
            Err(ModuleFileError)
        );
        assert_eq!(
            validate_universal_filename("fib", "other.hpy0.so", Platform::Linux),
            Err(ModuleFileError)
        );
    }

    #[test]
    fn all_h0_capabilities_fail_closed() {
        for capability in CAPABILITIES {
            assert_eq!(capability.state, CapabilityState::Unavailable);
            assert_eq!(
                require_capability(capability.id),
                Err(CapabilityError::Unavailable {
                    planned_milestone: capability.planned_milestone
                })
            );
        }
        assert_eq!(
            require_capability("future-api"),
            Err(CapabilityError::Unknown)
        );
        assert_eq!(IMPLEMENTED_FUNCTIONS, &[] as &[&str]);
        for function in PLANNED_FUNCTIONS {
            assert_eq!(
                require_function(function.name),
                Err(CapabilityError::Unavailable {
                    planned_milestone: function.planned_milestone
                })
            );
        }
        assert_eq!(
            require_function("HPy_Future"),
            Err(CapabilityError::Unknown)
        );
    }

    #[test]
    fn published_manifest_matches_typed_inventory() {
        for needle in [
            UPSTREAM.hpy_version,
            UPSTREAM.hpy_git_tag,
            UPSTREAM.hpy_docs_revision,
            UPSTREAM.hpy_sdist_sha256,
            UPSTREAM.ahpy_git_revision,
            UNIVERSAL_ABI.tag,
        ] {
            assert!(
                MANIFEST_TOML.contains(needle),
                "missing manifest value: {needle}"
            );
        }
        for capability in CAPABILITIES {
            assert!(MANIFEST_TOML.contains(&format!("id = \"{}\"", capability.id)));
        }
        for function in PLANNED_FUNCTIONS {
            assert!(MANIFEST_TOML.contains(&format!("\"{}\"", function.name)));
        }
    }
}
